apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-travel-budget
  namespace: my-travel-budget
  labels:
    app: my-travel-budget
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-travel-budget
  template:
    metadata:
      labels:
        app: my-travel-budget
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: my-travel-budget
          image: ghcr.io/aamad777/my-travel-budget:169ed5d
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
