// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

function createSupabaseClient() {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY
        ? ["VITE_SUPABASE_PUBLISHABLE_KEY"]
        : []),
    ];

    const message = `Missing Supabase environment variable(s): ${missing.join(
      ", ",
    )}.`;

    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {
        storage:
          typeof window !== "undefined" ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    },
  );
}

let supabaseClient:
  | ReturnType<typeof createSupabaseClient>
  | undefined;

export const supabase = new Proxy(
  {} as ReturnType<typeof createSupabaseClient>,
  {
    get(_, property, receiver) {
      if (!supabaseClient) {
        supabaseClient = createSupabaseClient();
      }

      return Reflect.get(supabaseClient, property, receiver);
    },
  },
);
